yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
 '@aws-sdk/config-resolver@*':
  dependencies:
   '@aws-sdk/node-config-provider': '*'
 '@aws-sdk/middleware-endpoint-discovery@*':
  dependencies:
   '@aws-sdk/node-config-provider': '*'
 '@aws-sdk/middleware-retry@*':
  dependencies:
   '@aws-sdk/node-config-provider': '*'
   '@aws-sdk/smithy-client': '*'
 '@aws-sdk/util-dynamodb@*':
  dependencies:
   '@aws-sdk/client-dynamodb': '*'
 'aws-sdk-client-mock@*':
   dependencies:
    'tslib': '*'
